# Generated by Django 6.0.2 on 2026-04-01 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
