# Generated by Django 6.0.2 on 2026-04-04 17:19

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=shop.models.product_image_upload_to, verbose_name='Фото'),
        ),
    ]
