# Generated by Django 6.0.2 on 2026-04-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Можна лишити порожнім — збережеться з назви (латиницею).', max_length=120, unique=True, verbose_name='Slug (для URL)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Порожньо — згенерується з заголовка.', max_length=220, unique=True, verbose_name='Slug (URL)'),
        ),
    ]
