# Generated by Django 6.0.2 on 2026-04-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_product_slug_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Можна лишити порожнім — збережеться з назви (укр./лат.).', max_length=120, unique=True, verbose_name='Slug (для URL)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Порожньо — згенерується з заголовка (укр./лат.).', max_length=220, unique=True, verbose_name='Slug (URL)'),
        ),
    ]
