# Generated by Django 6.0.2 on 2026-04-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_slug_allow_unicode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Порожньо — згенерується латиницею; якщо назва лише кирилицею — буде технічний slug (c-…).', max_length=120, unique=True, verbose_name='Slug (для URL)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Порожньо — латиниця з заголовка; якщо лише кирилиця — технічний slug (p-…).', max_length=220, unique=True, verbose_name='Slug (URL)'),
        ),
    ]
